// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEym7lpr7399ZGjv_nB06TfoNZnNRLAlI',
    appId: '1:1084088522203:android:d95d0663f5a756534d83fe',
    messagingSenderId: '1084088522203',
    projectId: 'projeto-de-despesas',
    storageBucket: 'projeto-de-despesas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBBaZiQh1PJF_DT--Ety1ixD9sdy2rCMw',
    appId: '1:1084088522203:ios:a5e92be9df759a014d83fe',
    messagingSenderId: '1084088522203',
    projectId: 'projeto-de-despesas',
    storageBucket: 'projeto-de-despesas.firebasestorage.app',
    iosBundleId: 'com.example.moneyAssistant2608',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDklKrheAYZ8ZN982PqUCUMeT8LbIgsCHM',
    appId: '1:1084088522203:web:8ff93ebdf44289444d83fe',
    messagingSenderId: '1084088522203',
    projectId: 'projeto-de-despesas',
    authDomain: 'projeto-de-despesas.firebaseapp.com',
    storageBucket: 'projeto-de-despesas.firebasestorage.app',
    measurementId: 'G-FZ4EQ0HRW7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBBaZiQh1PJF_DT--Ety1ixD9sdy2rCMw',
    appId: '1:1084088522203:ios:1c26735c759707fa4d83fe',
    messagingSenderId: '1084088522203',
    projectId: 'projeto-de-despesas',
    storageBucket: 'projeto-de-despesas.firebasestorage.app',
    iosBundleId: 'com.example.controleFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDklKrheAYZ8ZN982PqUCUMeT8LbIgsCHM',
    appId: '1:1084088522203:web:2bbcfa686aa1a3f14d83fe',
    messagingSenderId: '1084088522203',
    projectId: 'projeto-de-despesas',
    authDomain: 'projeto-de-despesas.firebaseapp.com',
    storageBucket: 'projeto-de-despesas.firebasestorage.app',
    measurementId: 'G-8ZBXPR0DVX',
  );

}